import Link from "next/link";
import { ArrowLeft, Blocks, CheckCircle2, Database, Headphones, ShieldCheck } from "lucide-react";
import { ProductCard } from "@/components/product-card";
import { DemoForm } from "@/components/demo-form";
import { FaqList } from "@/components/faq-list";
import { SectionTitle } from "@/components/section-title";
import { getApprovedTestimonials, getFaqs, getProducts, getServices } from "@/services";

export default function Home() {
  const products=getProducts(), services=getServices(), testimonials=getApprovedTestimonials();
  return <main id="main">
    <section className="hero section-pad"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">راهکارهای یکپارچه مالی و اداری</span><h1>داده‌ها را به جریان کاری دقیق و قابل کنترل تبدیل کنید.</h1><p>داده نگار ماتریس، مجموعه‌ای از نرم‌افزارهای راهبردی برای مدیریت مالی، منابع انسانی، حقوق و دستمزد، انبار و اتوماسیون اداری ارائه می‌کند.</p><div className="actions"><Link className="btn primary" href="/demo">درخواست دمو <ArrowLeft size={18}/></Link><Link className="btn ghost" href="/products">مشاهده محصولات</Link></div><div className="source-note">اطلاعات این سایت از کاتالوگ رسمی شرکت استخراج شده است.</div></div><div className="hero-visual" aria-label="معماری یکپارچه راهکارهای سازمانی"><div className="visual-core"><Database/><strong>هسته یکپارچه</strong><span>مالی و اداری</span></div><div className="orbit-item o1">منابع انسانی</div><div className="orbit-item o2">حقوق</div><div className="orbit-item o3">انبار و اموال</div><div className="orbit-item o4">اتوماسیون</div></div></div></section>
    <section className="section-pad"><div className="container split"><div><SectionTitle kicker="درباره شرکت" title="نرم‌افزار برای فرآیندهای واقعی سازمان"/><p className="lead">محصولات داده نگار ماتریس بر فرآیندهای مالی و اداری، به‌ویژه نیازهای دانشگاه‌ها و سازمان‌ها تمرکز دارند و میان واحدهای منابع انسانی، مالی، اعتبارات، انبار و مکاتبات ارتباط ایجاد می‌کنند.</p><Link className="text-link" href="/about">بیشتر درباره شرکت <ArrowLeft size={16}/></Link></div><div className="feature-panel"><div><Blocks/><b>معماری یکپارچه</b><span>ارتباط بین سامانه‌های مالی و اداری</span></div><div><ShieldCheck/><b>کنترل دسترسی</b><span>سطوح دسترسی برای کاربران سازمانی</span></div><div><Database/><b>گزارش‌گیری</b><span>گزارش‌های پویا، تجمیعی و مقایسه‌ای</span></div><div><Headphones/><b>راهکار سازمانی</b><span>متناسب با گردش‌کارهای چندواحدی</span></div></div></div></section>
    <section className="section-pad soft"><div className="container"><SectionTitle kicker="محصولات" title="یک مجموعه، برای جریان‌های کاری به‌هم‌پیوسته" description="هر محصول بر مبنای قابلیت‌های ذکرشده در کاتالوگ رسمی معرفی شده است."/><div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div><div className="center"><Link className="btn ghost" href="/products">همه محصولات</Link></div></div></section>
    <section className="section-pad"><div className="container"><SectionTitle kicker="خدمات" title="همراهی در مسیر استقرار و بهره‌برداری"/><div className="service-grid">{services.map((s,i)=><article className="service-card" key={s.id}><span>۰{i+1}</span><h3>{s.title}</h3><p>{s.description}</p></article>)}</div></div></section>
    <section className="section-pad dark"><div className="container"><SectionTitle kicker="چرا ماتریس" title="برای پیچیدگی‌های واقعی سازمان طراحی شده"/><div className="advantages"><div><CheckCircle2/><b>پوشش فرآیندهای تخصصی</b><p>از احکام و حقوق تا کنترل تخصیص و گردش مکاتبات</p></div><div><CheckCircle2/><b>یکپارچگی بین واحدها</b><p>انتقال اطلاعات میان منابع انسانی، مالی و سامانه‌های تحت وب</p></div><div><CheckCircle2/><b>گزارش‌های مدیریتی</b><p>گزارش‌های پویا، ماتریسی و خروجی‌های Excel و Word</p></div></div></div></section>
    {testimonials.length>0&&<section className="section-pad"><div className="container"><SectionTitle kicker="نظرات مشتریان" title="تجربه مشتریان"/><div className="quote-grid">{testimonials.map(t=><blockquote key={t.id}>{t.text}<footer>{t.name}، {t.company}</footer></blockquote>)}</div></div></section>}
    <section className="section-pad soft"><div className="container demo-split"><div><SectionTitle kicker="درخواست دمو" title="راهکار مناسب سازمانتان را دقیق‌تر ببینید" description="فرم را تکمیل کنید تا درخواست شما در این نسخه به‌صورت محلی ثبت شود."/><ul className="tick-list"><li>انتخاب محصول موردنظر</li><li>تعیین روش و زمان مناسب تماس</li><li>آماده برای اتصال به API در آینده</li></ul></div><DemoForm compact/></div></section>
    <section className="section-pad"><div className="container narrow"><SectionTitle kicker="پرسش‌های متداول" title="پاسخ‌های کوتاه و روشن"/><FaqList items={getFaqs().slice(0,6)}/><div className="center"><Link className="text-link" href="/faq">مشاهده همه پرسش‌ها <ArrowLeft size={16}/></Link></div></div></section>
    <section className="contact-strip"><div className="container"><div><span>برای شروع گفتگو آماده‌اید؟</span><h2>نیاز سازمانتان را با ما مطرح کنید.</h2></div><div className="actions"><Link className="btn light" href="/contact">تماس با ما</Link><Link className="btn outline-light" href="/demo">درخواست دمو</Link></div></div></section>
  </main>;
}
